export const FormSections = {
  HEADING: "Heading",
  EDUCATION: "Education",
  EXPERIENCE: "Experience",
  SKILLS: "Skills",
  CERTIFICATIONS: "Certifications",
  LANGUAGES: "Languages",
  REFERENCES: "References",
  ACHIEVEMENTS: "Achievements",
  INTERESTS: "Interests",
  SUMMARY: "Summary",
  PERSONALPROJECTS: "Personal Projects",
  FINALIZE: "Finalize",
  ADDADDITIONALSECTION: "Add additional section",
};
